### ISSUE TITLE
[Feature]: 로컬 회원가입 및 로그인

### ISSUE THREAD

**Issue by InHyeok-J** [gdsc-seoultech/DontSleepDriver_Back#3]
## 기능 설명
- 로컬 회원가입 및 로그인

## Tasks
- [x] config 파일 설정(데이터 베이스 및 jwt env파일관리)
- [x] 회원가입
- [x] 회원가입-휴대폰 or 이메일 인증 확인
- [x] 로그인 jwt 발급
- [x] 도커 개발환경 구성
